# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-12-09T17:58:22Z"
  labels:
    app: p-moe-sticker-bot
  name: p-moe-sticker-bot
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: NGINX_PORT
      value: "443"
    - name: NGINX_CERT
      value: /certs/live/emoji.1yo.cc/fullchain.pem
    - name: WEBAPP_ROOT
      value: /webapp
    - name: WEBAPP_ADDR
      value: 127.0.0.1:3921/webapp
    - name: NGINX_KEY
      value: /certs/live/emoji.1yo.cc/privkey.pem
    image: ghcr.io/star-39/moe-sticker-bot:msb_nginx_aarch64
    name: msbnginx
    ports:
    - containerPort: 443
      hostPort: 443
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /certs
      name: etc-letsencrypt-host-0
    - mountPath: /webapp/data
      name: moe-sticker-bot-webapp-data-ed

  - command:
    - /moe-sticker-bot
    - --bot_token=6613391715:AAEpAgWSYUW7DcHoXNgTdJgxtMilm7NiIXs
    - --webapp
    - --webapp_url
    - https://emjdl.1yo.cc/
    - --webapp_data_dir
    - /webapp/data/
    - --webapp_listen_addr
    - 127.0.0.1:3921
    - --use_db
    - --db_addr
    - 10.88.0.1:3306
    - --db_user
    - root
    - --db_pass
    - 8501
    image: ghcr.io/exoticskywing/moe-sticker-bot:latest
    name: msb
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /webapp/data
      name: moe-sticker-bot-webapp-data-ed

  - args:
    - mariadbd
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: 8501
    image: docker.io/library/mariadb:10.6
    name: msbmariadb
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: moe-sticker-bot-db-pvc

  hostname: p-moe-sticker-bot

  volumes:
  - hostPath:
      path: /etc/letsencrypt
      type: Directory
    name: etc-letsencrypt-host-0
  - name: moe-sticker-bot-webapp-data-ed
    emptyDir: {}
  - name: moe-sticker-bot-db-pvc
    persistentVolumeClaim:
     claimName: moe-sticker-bot-db-pvc
status: {}

